select*from customer ;

-- Q1 what is the total revenue generated by male and female  customer

select gender,sum(purchase_amount) as revenue
 from customer
 group by Gender;

-- Q2 which customer used a discount  but still spent more than the average purchase amount -- 

select customer_id,purchase_amount from customer
where discount_applied="yes" and purchase_amount>=(select avg(purchase_amount)from customer);
 
--  Q3 which are the top 5 product with highest average review rating
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS "Average review rating"
FROM 
    customer
GROUP BY 
    item_purchased
ORDER BY 
    "Average review rating" DESC
LIMIT 5;

-- Q4 compare the average purchase Amount betweeen standard and express shipping 
select shipping_type,
round(avg(purchase_amount),2) 
from customer
where shipping_type in("Standard","Express")
group by shipping_type;

-- Q5 Do subscribed customer spend moral? Compare averager spend and total revenue between subscriber and non-sunscriber
SELECT
 subscription_status,
count(customer_id) as Total_Customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2)as total_revenue
FROM 
customer
GROUP BY
subscription_status
ORDER BY 
total_revenue , avg_spend desc;

-- Q6 WHICH 5 PRODUCT HAVE A HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNT APPLIED??-- 

SELECT
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END) / COUNT(*)) * 100,
        2
    ) AS discount_percentage
FROM
    customer
GROUP BY
    item_purchased
ORDER BY
    discount_percentage DESC
LIMIT 5;


-- Q7 Segment customers into new Returning and loyal based on their total  
-- number or previous purchase and show the count of each segment 

with customer_type as(
select customer_id, previous_purchases,
CASE 
when previous_purchases = 1 then "NEW"
when previous_purchases between 2 AND 4 then "RETURNING"
ELSE "LOYAL"
END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers" 
from customer_type
group by customer_segment;

-- Q9 are customer who are repeat buyer (more than 5 purchase ) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

-- Q10 what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



 
 
 